// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Board = require("./board.bs.js");
var React = require("react");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(Board.make, { }));
}

var make = App;

exports.make = make;
/* Board Not a pure module */
