// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Cells = require("./cells.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Indicator = require("./indicator.bs.js");
var Model_board = require("./model_board.bs.js");
var Model_indicator = require("./model_indicator.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function Board(Props) {
  var match = React.useReducer(Model_board.State[/* reducer */1], Model_board.State[/* initial_state */0]);
  var dispatch = match[1];
  var state = match[0];
  var match$1 = React.useReducer(Model_indicator.State[/* reducer */1], Model_indicator.State[/* initial_state */0]);
  var indicatorDispatch = match$1[1];
  var indicatorState = match$1[0];
  var handleClick = function (e) {
    e.preventDefault();
    var element = e.target;
    var position_000 = element.parentNode.id;
    var position_001 = element.id;
    var position = /* tuple */[
      position_000,
      position_001
    ];
    var match = state[/* turn */0];
    switch (match) {
      case "O" : 
          Curry._1(dispatch, /* Circle */Block.__(0, [position]));
          break;
      case "X" : 
          Curry._1(dispatch, /* Cross */Block.__(1, [position]));
          break;
      default:
        throw [
              Caml_builtin_exceptions.match_failure,
              /* tuple */[
                "board.re",
                14,
                8
              ]
            ];
    }
    return Curry._1(indicatorDispatch, state[/* move */1]);
  };
  var indicator = function (param) {
    var match = indicatorState[/* status */0];
    switch (match) {
      case 0 : 
          return React.createElement(Indicator.make, {
                      status: "Draw"
                    });
      case 1 : 
          return React.createElement(Indicator.make, {
                      status: "Winner"
                    });
      case 2 : 
          return React.createElement(Indicator.make, {
                      status: "Ongoing"
                    });
      
    }
  };
  console.log(indicator);
  var board = $$Array.mapi((function (index, item) {
          return React.createElement("div", {
                      id: String(index)
                    }, React.createElement(Cells.make, {
                          row: item,
                          event: handleClick,
                          key: String(index)
                        }));
        }), state[/* move */1]);
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "board"
                }, board), React.createElement("div", {
                  className: "inicator"
                }));
}

var make = Board;

exports.make = make;
/* Cells Not a pure module */
