// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Indicator(Props) {
  var status = Props.status;
  return React.createElement("div", undefined, status);
}

var make = Indicator;

exports.make = make;
/* react Not a pure module */
