// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Login(Props) {
  return React.createElement("div", {
              style: {
                padding: "20px"
              }
            }, React.createElement("input", undefined));
}

var make = Login;

exports.make = make;
/* react Not a pure module */
