// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

var Action = /* module */[];

var initial_state_001 = /* move */$$Array.make_matrix(3, 3, "");

var initial_state = /* record */[
  /* turn */"X",
  initial_state_001
];

function reducer(state, action) {
  if (action.tag) {
    var match = action[0];
    Caml_array.caml_array_set(Caml_array.caml_array_get(state[/* move */1], match[0]), match[1], "X");
    return /* record */[
            /* turn */"O",
            /* move */state[/* move */1]
          ];
  } else {
    var match$1 = action[0];
    Caml_array.caml_array_set(Caml_array.caml_array_get(state[/* move */1], match$1[0]), match$1[1], "O");
    return /* record */[
            /* turn */"X",
            /* move */state[/* move */1]
          ];
  }
}

var State = /* module */[
  /* initial_state */initial_state,
  /* reducer */reducer
];

exports.Action = Action;
exports.State = State;
/* initial_state Not a pure module */
