// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

var Player = /* module */[];

var Status = /* module */[];

function checker(cells) {
  var pattern1_000 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 0), 0);
  var pattern1_001 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 0), 1);
  var pattern1_002 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 0), 2);
  var pattern1 = /* tuple */[
    pattern1_000,
    pattern1_001,
    pattern1_002
  ];
  var pattern2_000 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 1), 0);
  var pattern2_001 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 1), 1);
  var pattern2_002 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 1), 2);
  var pattern2 = /* tuple */[
    pattern2_000,
    pattern2_001,
    pattern2_002
  ];
  var pattern3_000 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 2), 0);
  var pattern3_001 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 2), 1);
  var pattern3_002 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 2), 2);
  var pattern3 = /* tuple */[
    pattern3_000,
    pattern3_001,
    pattern3_002
  ];
  var pattern4_000 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 0), 0);
  var pattern4_001 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 1), 0);
  var pattern4_002 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 2), 0);
  var pattern4 = /* tuple */[
    pattern4_000,
    pattern4_001,
    pattern4_002
  ];
  var pattern5_000 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 0), 1);
  var pattern5_001 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 1), 1);
  var pattern5_002 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 2), 1);
  var pattern5 = /* tuple */[
    pattern5_000,
    pattern5_001,
    pattern5_002
  ];
  var pattern6_000 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 0), 2);
  var pattern6_001 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 1), 2);
  var pattern6_002 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 2), 2);
  var pattern6 = /* tuple */[
    pattern6_000,
    pattern6_001,
    pattern6_002
  ];
  var pattern7_000 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 0), 0);
  var pattern7_001 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 1), 1);
  var pattern7_002 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 2), 2);
  var pattern7 = /* tuple */[
    pattern7_000,
    pattern7_001,
    pattern7_002
  ];
  var pattern8_000 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 0), 2);
  var pattern8_001 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 1), 1);
  var pattern8_002 = Caml_array.caml_array_get(Caml_array.caml_array_get(cells, 2), 0);
  var pattern8 = /* tuple */[
    pattern8_000,
    pattern8_001,
    pattern8_002
  ];
  if (Caml_obj.caml_equal(pattern1, /* tuple */[
          "X",
          "X",
          "X"
        ]) || Caml_obj.caml_equal(pattern1, /* tuple */[
          "O",
          "O",
          "O"
        ]) || Caml_obj.caml_equal(pattern2, /* tuple */[
          "X",
          "X",
          "X"
        ]) || Caml_obj.caml_equal(pattern2, /* tuple */[
          "O",
          "O",
          "O"
        ]) || Caml_obj.caml_equal(pattern3, /* tuple */[
          "X",
          "X",
          "X"
        ]) || Caml_obj.caml_equal(pattern3, /* tuple */[
          "O",
          "O",
          "O"
        ]) || Caml_obj.caml_equal(pattern4, /* tuple */[
          "X",
          "X",
          "X"
        ]) || Caml_obj.caml_equal(pattern4, /* tuple */[
          "O",
          "O",
          "O"
        ]) || Caml_obj.caml_equal(pattern5, /* tuple */[
          "X",
          "X",
          "X"
        ]) || Caml_obj.caml_equal(pattern5, /* tuple */[
          "O",
          "O",
          "O"
        ]) || Caml_obj.caml_equal(pattern6, /* tuple */[
          "X",
          "X",
          "X"
        ]) || Caml_obj.caml_equal(pattern6, /* tuple */[
          "O",
          "O",
          "O"
        ]) || Caml_obj.caml_equal(pattern7, /* tuple */[
          "X",
          "X",
          "X"
        ]) || Caml_obj.caml_equal(pattern7, /* tuple */[
          "O",
          "O",
          "O"
        ]) || Caml_obj.caml_equal(pattern8, /* tuple */[
          "X",
          "X",
          "X"
        ])) {
    return true;
  } else {
    return Caml_obj.caml_equal(pattern8, /* tuple */[
                "O",
                "O",
                "O"
              ]);
  }
}

var Game = /* module */[/* checker */checker];

var initial_state_001 = /* move */$$Array.make_matrix(3, 3, "");

var initial_state = /* record */[
  /* turn : Cross */1,
  initial_state_001,
  /* status : Ongoing */2,
  /* winner */""
];

function moveReducer(state, action) {
  if (action) {
    if (action[0]) {
      var match = action[1];
      Caml_array.caml_array_set(Caml_array.caml_array_get(state[/* move */1], match[0]), match[1], "X");
      var match$1 = checker(state[/* move */1]);
      var match$2 = checker(state[/* move */1]);
      return /* record */[
              /* turn : Circle */0,
              /* move */state[/* move */1],
              /* status */match$1 ? /* Winner */1 : /* Ongoing */2,
              /* winner */match$2 ? "X" : ""
            ];
    } else {
      var match$3 = action[1];
      Caml_array.caml_array_set(Caml_array.caml_array_get(state[/* move */1], match$3[0]), match$3[1], "O");
      var match$4 = checker(state[/* move */1]);
      var match$5 = checker(state[/* move */1]);
      return /* record */[
              /* turn : Cross */1,
              /* move */state[/* move */1],
              /* status */match$4 ? /* Winner */1 : /* Ongoing */2,
              /* winner */match$5 ? "O" : ""
            ];
    }
  } else {
    return state;
  }
}

var State = /* module */[
  /* initial_state */initial_state,
  /* moveReducer */moveReducer
];

exports.Player = Player;
exports.Status = Status;
exports.Game = Game;
exports.State = State;
/* initial_state Not a pure module */
