// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var User = /* module */[];

function state(state$1) {
  if (state$1) {
    return "I am Logged In";
  } else {
    return "I am Not Logged In";
  }
}

var Auth = /* module */[/* state */state];

function User$Navbar(Props) {
  var name = Props.name;
  return React.createElement("div", {
              className: "navbar"
            }, React.createElement("div", {
                  className: "user"
                }, React.createElement("p", undefined, name)), React.createElement("div", {
                  className: "login"
                }, "I am Not Logged In"));
}

var Navbar = /* module */[/* make */User$Navbar];

exports.User = User;
exports.Auth = Auth;
exports.Navbar = Navbar;
/* react Not a pure module */
